import { validateContractPayload } from "@aura/contracts";
import { listTrustedPackageDetails } from "./library.mjs";

function normalizeText(value) {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function slugText(value) {
  return normalizeText(value).replace(/\s+/g, "_") || "item";
}

function titleFromPrompt(prompt) {
  const normalized = String(prompt || "").trim();
  if (!normalized) {
    return "Generated Circuit";
  }
  const compact = normalized.replace(/\s+/g, " ").slice(0, 64);
  return compact.charAt(0).toUpperCase() + compact.slice(1);
}

function includesAny(haystack, needles) {
  const normalized = normalizeText(haystack);
  return needles.some((needle) => normalized.includes(normalizeText(needle)));
}

export function buildDeterministicIntentFromPrompt(prompt) {
  const userPrompt = String(prompt || "").trim();
  const wantsArduino = includesAny(userPrompt, ["arduino", "uno", "blink", "digital pin"]);
  const wantsLed = includesAny(userPrompt, ["led", "light", "indicator", "blink"]);
  const wantsResistor = includesAny(userPrompt, ["resistor", "220", "current limit", "led", "blink"]);

  const parts = [];
  if (wantsArduino) {
    parts.push({
      role: "controller",
      query: "Arduino Uno",
      quantity: 1,
      required: true,
    });
  }
  if (wantsLed) {
    parts.push({
      role: "indicator",
      query: includesAny(userPrompt, ["rgb"]) ? "rgb led" : "red led",
      quantity: 1,
      required: true,
    });
  }
  if (wantsResistor) {
    parts.push({
      role: "current_limit",
      query: "resistor",
      valueHint: includesAny(userPrompt, ["220"]) ? "220R" : "220R",
      quantity: 1,
      required: true,
      notes: "Added as a beginner LED current-limiting resistor.",
    });
  }

  if (!parts.length) {
    parts.push({
      role: "indicator",
      query: "red led",
      quantity: 1,
      required: true,
    });
  }

  const roles = new Set(parts.map((part) => part.role));
  const connections = [];
  if (roles.has("controller") && roles.has("current_limit") && roles.has("indicator")) {
    connections.push(
      {
        fromRole: "controller",
        fromPinHint: "digital output",
        toRole: "current_limit",
        netLabel: "SIG",
      },
      {
        fromRole: "current_limit",
        toRole: "indicator",
        toPinHint: "anode",
      },
      {
        fromRole: "indicator",
        fromPinHint: "cathode",
        toRole: "controller",
        toPinHint: "ground",
        netLabel: "GND",
      },
    );
  }

  return {
    schema: "aura.circuit_intent.v1",
    metadata: {
      title: titleFromPrompt(userPrompt),
      userPrompt: userPrompt || "Create a simple beginner circuit.",
      preferredView: "breadboard",
      createdBy: "aura_deterministic_fallback",
    },
    requirements: {
      goal: userPrompt || "Simple beginner circuit.",
      parts,
      ...(connections.length ? { connections } : {}),
      constraints: {
        allowSubstitutions: true,
        prioritizeSimplicity: true,
        maxPartCount: parts.reduce((sum, part) => sum + part.quantity, 0),
      },
    },
    reviewHints: [
      "Generated by deterministic fallback; review before treating as final user intent.",
    ],
  };
}

function packageSearchText(entry) {
  return normalizeText([
    entry.packageId,
    entry.slug,
    entry.name,
    entry.category,
    ...(entry.aliases ?? []),
    entry.component?.metadata?.description,
    ...(entry.component?.metadata?.tags ?? []),
    ...(entry.component?.aliases ?? []),
  ].filter(Boolean).join(" "));
}

function scorePackageForPart(part, entry) {
  const query = normalizeText(part.query);
  const role = normalizeText(part.role);
  const valueHint = normalizeText(part.valueHint);
  const searchText = packageSearchText(entry);
  let score = 0;
  const reasons = [];

  if (query && normalizeText(entry.name) === query) {
    score += 120;
    reasons.push("exact package name");
  }
  if ((entry.aliases ?? []).some((alias) => normalizeText(alias) === query)) {
    score += 110;
    reasons.push("exact alias");
  }
  if (query && searchText.includes(query)) {
    score += 70;
    reasons.push("query match");
  }
  if (valueHint && searchText.includes(valueHint)) {
    score += 45;
    reasons.push("value hint match");
  }
  if (role === "controller" && entry.category === "board") {
    score += 35;
    reasons.push("controller role maps to board package");
  }
  if (role === "indicator" && entry.category === "indicator") {
    score += 35;
    reasons.push("indicator role maps to indicator package");
  }
  if (role.includes("current") && entry.category === "passive") {
    score += 35;
    reasons.push("current-limit role maps to passive package");
  }
  if (entry.status === "trusted") {
    score += 10;
    reasons.push("trusted package");
  }

  return {
    score,
    reasons,
  };
}

export async function resolveCircuitIntent(intent) {
  const packages = await listTrustedPackageDetails();
  const matches = [];
  const unresolved = [];

  for (const part of intent.requirements.parts ?? []) {
    const ranked = packages
      .map((entry) => ({
        packageId: entry.packageId,
        slug: entry.slug,
        name: entry.name,
        category: entry.category,
        runtimeProfileId: entry.runtimeProfileId ?? entry.component?.runtimeProfileRef ?? null,
        component: entry.component,
        ...scorePackageForPart(part, entry),
      }))
      .filter((candidate) => candidate.score > 0)
      .sort((left, right) => right.score - left.score || left.name.localeCompare(right.name));

    if (!ranked.length || ranked[0].score < 35) {
      unresolved.push({
        role: part.role,
        query: part.query,
        reason: "No trusted curated package matched this requirement.",
      });
      continue;
    }

    matches.push({
      role: part.role,
      query: part.query,
      quantity: part.quantity,
      valueHint: part.valueHint ?? "",
      selected: {
        packageId: ranked[0].packageId,
        slug: ranked[0].slug,
        name: ranked[0].name,
        category: ranked[0].category,
        runtimeProfileId: ranked[0].runtimeProfileId,
        confidence: Math.min(1, Number((ranked[0].score / 160).toFixed(2))),
        reasons: ranked[0].reasons,
      },
      candidates: ranked.slice(0, 3).map((candidate) => ({
        packageId: candidate.packageId,
        name: candidate.name,
        confidence: Math.min(1, Number((candidate.score / 160).toFixed(2))),
        reasons: candidate.reasons,
      })),
      component: ranked[0].component,
    });
  }

  return {
    matches,
    unresolved,
  };
}

function referencePrefix(match) {
  const category = match.selected.category;
  const name = normalizeText(match.selected.name);
  if (category === "board") {
    return "U";
  }
  if (name.includes("resistor")) {
    return "R";
  }
  if (category === "indicator" || name.includes("led")) {
    return "D";
  }
  return "U";
}

function buildComponentsFromMatches(matches) {
  const counters = new Map();
  const components = [];
  const roleToComponentIds = new Map();

  for (const match of matches) {
    const quantity = Math.max(1, Number(match.quantity) || 1);
    for (let index = 0; index < quantity; index += 1) {
      const prefix = referencePrefix(match);
      const next = (counters.get(prefix) ?? 0) + 1;
      counters.set(prefix, next);

      const componentId = `${slugText(match.role)}_${next}`;
      const component = {
        id: componentId,
        packageId: match.selected.packageId,
        reference: `${prefix}${next}`,
        ...(match.valueHint ? { attrs: { value: match.valueHint } } : {}),
        ...(match.selected.runtimeProfileId ? { runtimeProfileId: match.selected.runtimeProfileId } : {}),
        placement: {
          x: 100 + components.length * 140,
          y: match.selected.category === "board" ? 120 : 150,
          rotationDeg: 0,
        },
      };
      components.push(component);

      const ids = roleToComponentIds.get(match.role) ?? [];
      ids.push(componentId);
      roleToComponentIds.set(match.role, ids);
    }
  }

  return {
    components,
    roleToComponentIds,
  };
}

function getComponentPackage(componentId, components, matches) {
  const component = components.find((entry) => entry.id === componentId);
  const match = matches.find((entry) => entry.selected.packageId === component?.packageId);
  return match?.component ?? null;
}

function selectPinForHint(componentPackage, hint, fallbackIndex = 0) {
  const pins = componentPackage?.pins ?? [];
  if (!pins.length) {
    return "1";
  }

  const normalizedHint = normalizeText(hint);
  const findPin = (tests) => pins.find((pin) => {
    const text = normalizeText([pin.id, pin.label, pin.side].filter(Boolean).join(" "));
    return tests.some((test) => text.includes(test));
  });

  if (normalizedHint.includes("ground") || normalizedHint === "gnd") {
    return findPin(["gnd", "ground", "cathode", " k"])?.id ?? pins[pins.length - 1].id;
  }
  if (normalizedHint.includes("digital") || normalizedHint.includes("output")) {
    return findPin(["d13", "digital", "io"])?.id ?? pins[0].id;
  }
  if (normalizedHint.includes("anode")) {
    return findPin(["anode", " a"])?.id ?? pins[0].id;
  }
  if (normalizedHint.includes("cathode")) {
    return findPin(["cathode", " k", "com"])?.id ?? pins[pins.length - 1].id;
  }

  return pins[Math.min(fallbackIndex, pins.length - 1)].id;
}

function buildNets(intent, components, roleToComponentIds, matches) {
  const connections = intent.requirements.connections ?? [];
  return connections.map((connection, index) => {
    const fromComponentId = roleToComponentIds.get(connection.fromRole)?.[0];
    const toComponentId = roleToComponentIds.get(connection.toRole)?.[0];
    const fromPackage = getComponentPackage(fromComponentId, components, matches);
    const toPackage = getComponentPackage(toComponentId, components, matches);

    return {
      id: connection.netLabel ? `net_${slugText(connection.netLabel)}` : `net_${index + 1}`,
      ...(connection.netLabel ? { label: connection.netLabel } : {}),
      connections: [
        {
          componentId: fromComponentId,
          pinId: selectPinForHint(fromPackage, connection.fromPinHint, 0),
        },
        {
          componentId: toComponentId,
          pinId: selectPinForHint(toPackage, connection.toPinHint, 1),
        },
      ].filter((entry) => entry.componentId),
    };
  }).filter((net) => net.connections.length > 0);
}

export async function compileCircuitIntentToIr(intent, resolution = null) {
  const validation = await validateContractPayload("circuit_intent.v1", intent);
  if (!validation.ok) {
    const error = new Error("circuit_intent payload is invalid.");
    error.validation = validation;
    throw error;
  }

  const resolved = resolution ?? await resolveCircuitIntent(intent);
  const { components, roleToComponentIds } = buildComponentsFromMatches(resolved.matches);
  const nets = buildNets(intent, components, roleToComponentIds, resolved.matches);
  const annotations = [
    ...resolved.unresolved.map((entry, index) => ({
      id: `unresolved_${index + 1}`,
      kind: "warning",
      text: `${entry.role}: ${entry.reason}`,
    })),
  ];

  if (!components.length) {
    annotations.push({
      id: "no_components",
      kind: "warning",
      text: "No components were compiled because no trusted package matches were available.",
    });
  }

  const circuitIr = {
    schema: "aura.circuit_ir.v1",
    metadata: {
      title: intent.metadata.title,
      description: intent.requirements.goal ?? "",
      sourceIntentId: slugText(intent.metadata.title),
      viewMode: intent.metadata.preferredView ?? "breadboard",
    },
    components,
    nets,
    ...(annotations.length ? { annotations } : {}),
  };

  const irValidation = await validateContractPayload("circuit_ir.v1", circuitIr);
  if (!irValidation.ok) {
    const error = new Error("compiled circuit_ir payload is invalid.");
    error.validation = irValidation;
    throw error;
  }

  return {
    circuitIr,
    resolution: resolved,
  };
}

export async function generateCircuitFromIntent(intent) {
  const resolution = await resolveCircuitIntent(intent);
  const { circuitIr } = await compileCircuitIntentToIr(intent, resolution);
  return {
    intent,
    resolution,
    circuitIr,
  };
}
